'''python
"""alembic revision --autogenerate -m "Initial migration"
"""

# revision identifiers, used by Alembic.
revision = "0001_initial"
 down_revision = None
 branch_labels = None
 depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("tg_id", sa.Integer(), nullable=False, unique=True),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("pan", sa.String(length=19), nullable=False, unique=True),
        sa.Column("cvv", sa.String(length=4), nullable=False),
        sa.Column("exp_date", sa.String(length=7), nullable=False),
        sa.Column("balance_usd", sa.Float(), nullable=True, default=0.0),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("card_id", sa.Integer(), sa.ForeignKey("cards.id"), nullable=False),
        sa.Column("amount_usd", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("external_tx_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("raw_data", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("cards")
    op.drop_table("users")
    # ### end Alembic commands ###
'''